// Chat
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const CLEAR_MESSAGE_LIST = 'CLEAR_MESSAGE_LIST';
export const CLEAR_USERS = 'CLEAR_USERS';
export const APPEND_TO_HISTORY = 'APPEND_TO_HISTORY';
export const UPDATE_USERLIST = 'UPDATE_USERLIST';
export const SET_SOCKET_CONNECTED = 'SET_SOCKET_CONNECTED';
export const SET_SOCKET_ERROR = 'SET_SOCKET_ERROR';
export const SET_CHAT_WIDTH = 'SET_CHAT_WIDTH';
export const SET_CURRENT_ROOMID = 'SET_CURRENT_ROOMID';

// Room
export const ADD_EMOJIS = 'ADD_EMOJIS';
export const UPDATE_MAIN_STATES = 'UPDATE_MAIN_STATES';
export const TOGGLE_CINEMAMODE = 'TOGGLE_CINEMAMODE';
export const UPDATE_POPULAR_EMOTE = 'UPDATE_POPULAR_EMOTE';

// User
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

// Media
export const UPDATE_MEDIA = 'UPDATE_MEDIA';
export const RESET_MEDIA = 'RESET_MEDIA';
export const UPDATE_MEDIA_URL = 'UPDATE_MEDIA_URL';
export const SWITCH_PLAY = 'SWITCH_PLAY';
export const SWITCH_MUTE = 'SWITCH_MUTE';
export const SET_VOLUME = 'SET_VOLUME';
export const SET_SUBS = 'SET_SUBS';
export const SET_CURRENT_SUBS = 'SET_CURRENT_SUBS';
export const SET_RAW_SUBS = 'SET_RAW_SUBS';
export const SET_SUBS_URL = 'SET_SUBS_URL';
export const SHOW_SUBS = 'SHOW_SUBS';
export const HIDE_SUBS = 'HIDE_SUBS';
export const TOGGLE_SUBS = 'TOGGLE_SUBS';
export const FETCH_SUBS = 'FETCH_SUBS';
export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST';
export const TOGGLE_SYNC = 'TOGGLE_SYNC';
export const SET_ADD_MEDIA_PENDING = 'SET_ADD_MEDIA_PENDING';

export const SET_REMOTE_PLAYING = 'SET_REMOTE_PLAYING';
export const SET_REMOTE_PAUSED = 'SET_REMOTE_PAUSED';

// Popups
export const ADD_POPUP = 'ADD_POPUP';
export const REMOVE_POPUP = 'REMOVE_POPUP';
export const CLEAR_POPUPS = 'CLEAR_POPUP';
export const TOGGLE_POPUP = 'TOGGLE_POPUP';

// Roomlist
export const UPDATE_ROOMLIST = 'UPDATE_ROOMLIST';
