export const ADD_MESSAGE = 'ADD_MESSAGE';
export const CLEAR_MESSAGE_LIST = 'CLEAR_MESSAGE_LIST';
export const APPEND_TO_HISTORY = 'APPEND_TO_HISTORY';
export const UPDATE_USERLIST = 'UPDATE_USERLIST';
export const UPDATE_SOCKET_STATE = 'UPDATE_SOCKET_STATE';

export const ADD_EMOJIS = 'ADD_EMOJIS';
export const UPDATE_MAIN_STATES = 'UPDATE_MAIN_STATES';
export const TOGGLE_CINEMAMODE = 'TOGGLE_CINEMAMODE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

// Media
export const UPDATE_MEDIA = 'UPDATE_MEDIA';
export const UPDATE_MEDIA_URL = 'UPDATE_MEDIA_URL';
export const SWITCH_PLAY = 'SWITCH_PLAY';
export const SWITCH_MUTE = 'SWITCH_MUTE';
export const SET_VOLUME = 'SET_VOLUME';
export const UPDATE_SUBS = 'UPDATE_SUBS';

export const UPDATE_ROOMLIST = 'UPDATE_ROOMLIST';
